import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { probeGame, probeScene } from '../src/runtime/probe/scene.js';

/**
 * Materialises the in-code stage 0 probe project into `public/probe-project/` so the
 * player entry point can load a real project from plain files. Generating it from the
 * same module the tests use keeps the JSON and the in-code document from drifting.
 *
 * Run with: pnpm tsx tools/write-probe-project.ts
 */

const root = fileURLToPath(new URL('..', import.meta.url));
const outDir = join(root, 'public', 'probe-project');

async function writeJson(relativePath: string, value: unknown): Promise<void> {
  const target = join(outDir, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  process.stdout.write(`wrote ${target}\n`);
}

const roundQuat = (q: readonly number[]) => q.map((value) => Number(value.toFixed(12)));

const sceneForDisk = {
  ...probeScene,
  entities: probeScene.entities.map((entity) => ({
    ...entity,
    transform: { ...entity.transform, rotation: roundQuat(entity.transform.rotation) },
  })),
};

await writeJson('game.json', probeGame);
await writeJson('scenes/main.scene.json', sceneForDisk);
await writeJson('assets/manifest.json', { schemaVersion: 1, assets: [] });
await writeJson('scripts/registry.json', { schemaVersion: 1, behaviors: [] });
await writeJson('README.md', '# Stage 0 probe\n\nGenerated by tools/write-probe-project.ts — do not edit by hand.\n');
