import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { probeGame, probeScene } from '../src/runtime/probe/scene.js';

/**
 * Materialises the in-code stage 0 probe project into `public/probe-project/` so the
 * player entry point can load a real project from plain files. Generating it from the
 * same module the tests use keeps the JSON and the in-code document from drifting.
 *
 * Run with: pnpm tsx tools/write-probe-project.ts
 */

const root = fileURLToPath(new URL('..', import.meta.url));
const outDir = join(root, 'public', 'probe-project');

/** Write one probe file from the exact bytes it should contain. */
async function writeText(relativePath: string, contents: string): Promise<void> {
  const target = join(outDir, relativePath);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents, 'utf8');
  process.stdout.write(`wrote ${target}\n`);
}

const roundQuat = (q: readonly number[]) => q.map((value) => Number(value.toFixed(12)));

const sceneForDisk = {
  ...probeScene,
  entities: probeScene.entities.map((entity) => ({
    ...entity,
    transform: { ...entity.transform, rotation: roundQuat(entity.transform.rotation) },
  })),
};

// The committed README is a JSON string of the markdown, so it keeps being written that way.
const readme = '# Stage 0 probe\n\nGenerated by tools/write-probe-project.ts — do not edit by hand.\n';

await writeText('game.json', `${JSON.stringify(probeGame, null, 2)}\n`);
await writeText('scenes/main.scene.json', `${JSON.stringify(sceneForDisk, null, 2)}\n`);
await writeText('assets/manifest.json', `${JSON.stringify({ schemaVersion: 1, assets: [] }, null, 2)}\n`);
await writeText('scripts/registry.json', `${JSON.stringify({ schemaVersion: 1, behaviors: [] }, null, 2)}\n`);
await writeText('README.md', `${JSON.stringify(readme, null, 2)}\n`);
